# Generated by Django 4.2.2 on 2023-06-26 03:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_product_section_product_img_product_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_information',
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.CreateModel(
            name='a_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', ckeditor.fields.RichTextField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
