# Generated by Django 4.2.2 on 2023-06-26 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_a_i_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='a_i',
            new_name='add_info',
        ),
    ]
