# Generated by Django 4.2.2 on 2023-06-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_slug_alter_product_product_information'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
