# Generated by Django 4.2.2 on 2023-06-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_add_info_brand_remove_add_info_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=' ', max_length=500, null=True, unique=True),
        ),
    ]
