# Generated by Django 4.2.2 on 2023-07-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
