# Generated by Django 4.2.2 on 2023-07-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_categories_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
