# Generated by Django 4.2.2 on 2023-07-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
    ]
