# Generated by Django 4.2.2 on 2023-07-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_user_order_user_order_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='User',
        ),
    ]
