# Generated by Django 4.2.2 on 2023-07-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(default=2, max_length=40, verbose_name='Order ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(default=2, max_length=128, verbose_name='Signature ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=254, verbose_name='Payment Status'),
        ),
    ]
