# Generated by Django 4.2.2 on 2023-07-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_order_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
