# Generated by Django 4.2.2 on 2023-07-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_rename_user_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
