# Generated by Django 4.2.2 on 2023-07-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_user_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='razor_pay_order_id',
            new_name='razorpay_order_id',
        ),
    ]
