# Generated by Django 4.2.2 on 2023-07-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
