# Generated by Django 4.2.2 on 2023-07-10 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_user_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='User',
            new_name='user',
        ),
    ]
