# Generated by Django 4.2.2 on 2023-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_payment_signature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_quality',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription_first',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription_second',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discription_third',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_charge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
