# Generated by Django 4.2.2 on 2023-07-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_order_company_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_info',
        ),
    ]
