# Generated by Django 4.2.2 on 2023-07-11 11:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_delete_add_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_information',
            field=ckeditor.fields.RichTextField(default='Transform your living spaces into stunning showcases of style and sophistication with our exquisite collection of furniture. Crafted with meticulous attention to detail and unparalleled quality, each piece is a testament to exceptional craftsmanship and timeless design', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='white', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='18 inches x 18 inches x 36 inches', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='Medium', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=110, null=True),
        ),
    ]
